apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  encryptedData:
    DB_USER: {{ .Values.sealedSecrets.dbUser | quote }}
    DB_PASSWORD: {{ .Values.sealedSecrets.dbPassword | quote }}
  template:
    type: Opaque
    metadata:
      name: app-secret
      namespace: {{ .Release.Namespace }}
      labels:
        {{- include "python-app.labels" . | nindent 8 }}
