apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app.fullname" . }}-app
  labels:
    app: flask-app
    {{- include "python-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort | default 5000 }}
      protocol: TCP
  selector:
    app: flask-app
